//IR sensor
//Connect sensor signal pin to analog pin A0 on Uno
//Mechatronics 530.421 Lab1
#define sensor A0 // Sharp IR (4-30cm, analog)

void setup() {
  Serial.begin(9600);
}

void loop() {
  float volts = analogRead(sensor)*0.0048828125;  // value from sensor * (5/1024)
  Serial.println(volts); // print out voltage generated by IR sensor
  delay(200); // small delay
}
